# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyvaluestore.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13keyvaluestore.proto\"\x1a\n\x0bLockRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"%\n\x0cLockResponse\x12\x15\n\rlock_acquired\x18\x01 \x01(\x08\"%\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbe\x01\n\rKeyValueStore\x12\x1a\n\x03Put\x12\x08.Request\x1a\t.Response\x12\x1a\n\x03Get\x12\x08.Request\x1a\t.Response\x12\x1d\n\x06\x44\x65lete\x12\x08.Request\x1a\t.Response\x12*\n\x0b\x41\x63quireLock\x12\x0c.LockRequest\x1a\r.LockResponse\x12*\n\x0bReleaseLock\x12\x0c.LockRequest\x1a\r.LockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyvaluestore_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCKREQUEST']._serialized_start=23
  _globals['_LOCKREQUEST']._serialized_end=49
  _globals['_LOCKRESPONSE']._serialized_start=51
  _globals['_LOCKRESPONSE']._serialized_end=88
  _globals['_REQUEST']._serialized_start=90
  _globals['_REQUEST']._serialized_end=127
  _globals['_RESPONSE']._serialized_start=129
  _globals['_RESPONSE']._serialized_end=156
  _globals['_KEYVALUESTORE']._serialized_start=159
  _globals['_KEYVALUESTORE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
