# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyvaluestore_pb2 as keyvaluestore__pb2


class KeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/KeyValueStore/Put',
                request_serializer=keyvaluestore__pb2.Request.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Response.FromString,
                )
        self.Get = channel.unary_unary(
                '/KeyValueStore/Get',
                request_serializer=keyvaluestore__pb2.Request.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Response.FromString,
                )
        self.Delete = channel.unary_unary(
                '/KeyValueStore/Delete',
                request_serializer=keyvaluestore__pb2.Request.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Response.FromString,
                )
        self.AcquireLock = channel.unary_unary(
                '/KeyValueStore/AcquireLock',
                request_serializer=keyvaluestore__pb2.LockRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.LockResponse.FromString,
                )
        self.ReleaseLock = channel.unary_unary(
                '/KeyValueStore/ReleaseLock',
                request_serializer=keyvaluestore__pb2.LockRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.LockResponse.FromString,
                )


class KeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=keyvaluestore__pb2.Request.FromString,
                    response_serializer=keyvaluestore__pb2.Response.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=keyvaluestore__pb2.Request.FromString,
                    response_serializer=keyvaluestore__pb2.Response.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=keyvaluestore__pb2.Request.FromString,
                    response_serializer=keyvaluestore__pb2.Response.SerializeToString,
            ),
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=keyvaluestore__pb2.LockRequest.FromString,
                    response_serializer=keyvaluestore__pb2.LockResponse.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=keyvaluestore__pb2.LockRequest.FromString,
                    response_serializer=keyvaluestore__pb2.LockResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/Put',
            keyvaluestore__pb2.Request.SerializeToString,
            keyvaluestore__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/Get',
            keyvaluestore__pb2.Request.SerializeToString,
            keyvaluestore__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/Delete',
            keyvaluestore__pb2.Request.SerializeToString,
            keyvaluestore__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/AcquireLock',
            keyvaluestore__pb2.LockRequest.SerializeToString,
            keyvaluestore__pb2.LockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/ReleaseLock',
            keyvaluestore__pb2.LockRequest.SerializeToString,
            keyvaluestore__pb2.LockResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
